### ISSUE TITLE
[Task] Set up GitHub Actions to mirror to Gitee

### ISSUE THREAD

**Issue by njzjz** [njzjz-bot/njzjz-bot#3]
Set up GitHub Actions to sync to Gitee. The Action file is copied from [dpdispatcher](https://github.com/deepmodeling/dpdispatcher/blob/master/.github/workflows/mirror_gitee.yml).

> [!Note]
> Please confirm the repository exists at https://gitee.com/deepmodeling.

> [!Note]
> Please close if the PR was created by mistake.

**Script:**
```py
import os

action_file = r"""name: Mirror to Gitee Repository

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    uses: deepmodeling/workflows/.github/workflows/mirror_gitee.yml@main
    secrets:
      SYNC_GITEE_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
"""

if not os.path.isfile(".github/workflows/mirror_gitee.yml"):
    os.makedirs(".github/workflows", exist_ok=True)
    with open(".github/workflows/mirror_gitee.yml", "w") as f:
        f.write(action_file)
```

**Running commands:**

```sh
multi-gitter run "python $PWD/run-mirror-gitee.py" --author-email "48687836+njzjz-bot@users.noreply.github.com" --author-name "njzjz-bot[bot]" -B mirror-gitee --fork -m 'CI: Mirror the repository to Gitee

See https://github.com/njzjz-bot/njzjz-bot/issues/3.
' -O deepmodeling --git-type cmd
```

**Comment by QG-phy** [comment]
@njzjz  Got an error in this workflow. see the message below.  Looks like I did not have access to the gitee repo. 

/usr/bin/docker run --name dd4328a6978a82b084db5a2e9c01ffbb3c29c_b79c1f --label 5dd432 --workdir /github/workspace --rm -e "ORGANIZATION" -e "SSH_PRIVATE_KEY" -e "INPUT_SOURCE-REPO" -e "INPUT_DESTINATION-REPO" -e "INPUT_DRY-RUN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/DeePTB/DeePTB":"/github/workspace" 5dd432:8a6978a82b084db5a2e9c01ffbb3c29c  "https://github.com/deepmodeling/DeePTB.git" "git@gitee.com:deepmodeling/DeePTB.git" "false"
WARNING: StrictHostKeyChecking disabled
SOURCE=https://github.com/deepmodeling/DeePTB.git
DESTINATION=git@gitee.com:deepmodeling/DeePTB.git
DRY RUN=false
Cloning into bare repository 'DeePTB.git'...
Warning: Permanently added 'gitee.com' (ED25519) to the list of known hosts.
[session-2d473e9e] Auth error: Access denied
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by njzjz** [comment]
We used Ping Tuo's SSH key. It seems Yibo canceled her access...

**Comment by njzjz** [comment]
I set up a new key.
